name: InventoryRemover
version: 0.1.0.1
author: Celeo
description: Banned items are removed from player and chest inventories
main: com.darktidegames.celeo.ir.InventoryRemover
commands:
  ir:
    usage: /<command>
    description: Reloads data from the configuration
    aliases: [ir, inventoryremover]
